services:
  telegraf:
    image: telegraf:${TELEGRAF_VERSION:-latest}
    command: -config /etc/telegraf/telegraf.conf -config-directory /etc/telegraf/telegraf.d
    restart: always
    hostname: telegraf
    volumes:
      - ../files/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ../files/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - dokploy-network

  influxdb:
    image: influxdb:${INFLUXDB_VERSION:-latest}
    restart: always
    hostname: influxdb
    environment:
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin} # Define in Dokploy environment
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password} # Define in Dokploy environment
    volumes:
      - ../files/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - ../files/influxdb:/var/lib/influxdb:rw
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.influxdb.rule=Host(`${INFLUXDB_HOST:-influxdb.example.com}`)" # Define INFLUXDB_HOST in Dokploy
      - "traefik.http.routers.influxdb.entrypoints=websecure"
      - "traefik.http.routers.influxdb.tls.certresolver=letsencrypt"
      - "traefik.http.services.influxdb.loadbalancer.server.port=8086"

  chronograf:
    image: chronograf:${CHRONOGRAF_VERSION:-latest}
    restart: always
    hostname: chronograf
    environment:
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER:-admin} # Define in Dokploy environment
      - INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password} # Define in Dokploy environment
      - KAPACITOR_URL=http://kapacitor:9092
      - KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER:-admin} # Define in Dokploy environment
      - KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password} # Define in Dokploy environment
    volumes:
      - ../files/chronograf:/var/lib/chronograf:rw
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.chronograf.rule=Host(`${CHRONOGRAF_HOST:-chronograf.example.com}`)" # Define CHRONOGRAF_HOST in Dokploy
      - "traefik.http.routers.chronograf.entrypoints=websecure"
      - "traefik.http.routers.chronograf.tls.certresolver=letsencrypt"
      - "traefik.http.services.chronograf.loadbalancer.server.port=8888"

  kapacitor:
    image: kapacitor:${KAPACITOR_VERSION:-latest}
    restart: always
    hostname: kapacitor
    volumes:
      - ../files/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ../files/kapacitor:/var/lib/kapacitor:rw
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kapacitor.rule=Host(`${KAPACITOR_HOST:-kapacitor.example.com}`)" # Define KAPACITOR_HOST in Dokploy
      - "traefik.http.routers.kapacitor.entrypoints=websecure"
      - "traefik.http.routers.kapacitor.tls.certresolver=letsencrypt"
      - "traefik.http.services.kapacitor.loadbalancer.server.port=9092"

networks:
  dokploy-network:
    external: true
