services:
  telegraf:
    image: 'telegraf:${TELEGRAF_VERSION:-latest}'
    restart: always
    hostname: telegraf
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - dokploy-network
  influxdb:
    image: 'influxdb:1.8'
    restart: always
    hostname: influxdb
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - '../files/config/influxdb:/etc/influxdb:ro'
      - '../files/influxdb:/var/lib/influxdb:rw'
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.influxdb.rule=Host(`${INFLUXDB_HOST:-influxdb.iotwise.com.au}`)
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.tls.certresolver=letsencrypt
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
  chronograf:
    image: 'chronograf:${CHRONOGRAF_VERSION:-latest}'
    restart: always
    hostname: chronograf
    environment:
      - 'INFLUXDB_URL=http://influxdb:8086'
      - 'INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
      - 'KAPACITOR_URL=http://kapacitor:9092'
      - 'KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
      - ./scripts/fix_permissions_chronograph.sh:/scripts/entrypoint.sh
    entrypoint: [ "sh", "./scripts/entrypoint.sh" ]
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.chronograf.rule=Host(`${CHRONOGRAF_HOST:-chronograf.iotwise.com.au}`)
      - traefik.http.routers.chronograf.entrypoints=websecure
      - traefik.http.routers.chronograf.tls.certresolver=letsencrypt
      - traefik.http.services.chronograf.loadbalancer.server.port=8888
  kapacitor:
    image: 'kapacitor:${KAPACITOR_VERSION:-latest}'
    restart: always
    hostname: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_PASSWORD=password
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
      - ./scripts/entrypoint.sh:/scripts/entrypoint.sh
    entrypoint: ["sh", "./scripts/entrypoint.sh"]
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.kapacitor.rule=Host(`${KAPACITOR_HOST:-kapacitor.iotwise.com.au}`)
      - traefik.http.routers.kapacitor.entrypoints=websecure
      - traefik.http.routers.kapacitor.tls.certresolver=letsencrypt
      - traefik.http.services.kapacitor.loadbalancer.server.port=9092

networks:
  dokploy-network:
    driver: bridge
