version: "3.8"

services:
  telegraf:
    image: 'telegraf:1.23.4'
    restart: always
    hostname: telegraf
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  influxdb:
    image: 'influxdb:1.8'
    restart: always
    hostname: influxdb
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - influxdb-config:/etc/influxdb:ro
      - influxdb-data:/var/lib/influxdb:rw
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.influxdb.rule=Host(`${INFLUXDB_HOST:-influxdb.iotwise.com.au}`)
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.tls.certresolver=letsencrypt
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8086/health"]
      interval: 10s
      timeout: 5s
      retries: 3

  chronograf:
    image: 'chronograf:1.10.0'
    restart: always
    hostname: chronograf
    environment:
      - 'INFLUXDB_URL=http://influxdb:8086'
      - 'INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
      - 'KAPACITOR_URL=http://kapacitor:9092'
      - 'KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - chronograf-data:/var/lib/chronograf:rw
      - ./scripts/fix_permissions_chronograf.sh:/scripts/fix_permissions_chronograf.sh
    entrypoint: ["sh", "/scripts/fix_permissions_chronograf.sh"]
    depends_on:
      - influxdb
      - kapacitor
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.chronograf.rule=Host(`${CHRONOGRAF_HOST:-chronograf.iotwise.com.au}`)
      - traefik.http.routers.chronograf.entrypoints=websecure
      - traefik.http.routers.chronograf.tls.certresolver=letsencrypt
      - traefik.http.services.chronograf.loadbalancer.server.port=8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  kapacitor:
    image: 'kapacitor:1.6.6'
    restart: always
    hostname: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - KAPACITOR_INFLUXDB_0_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - kapacitor-data:/var/lib/kapacitor:rw
      - ./scripts/entrypoint.sh:/scripts/entrypoint.sh
    entrypoint: ["sh", "/scripts/entrypoint.sh"]
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kapacitor.rule=Host(`${KAPACITOR_HOST:-kapacitor.iotwise.com.au}`)
      - traefik.http.routers.kapacitor.entrypoints=websecure
      - traefik.http.routers.kapacitor.tls.certresolver=letsencrypt
      - traefik.http.services.kapacitor.loadbalancer.server.port=9092
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9092/kapacitor/v1/ping"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  dokploy-network:
    driver: bridge

volumes:
  influxdb-config:
  influxdb-data:
  chronograf-data:
  kapacitor-data:
