services:
  traefik:
    image: 'traefik:v2.10' # Use the latest Traefik version
    container_name: traefik
    restart: always
    command:
      - --api.dashboard=true # Enable the Traefik dashboard
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false # Only containers with traefik.enable=true will be proxied
      - --entrypoints.web.address=:80 # HTTP entry point
      - --entrypoints.websecure.address=:443 # HTTPS entry point
      - --certificatesresolvers.letsencrypt.acme.httpchallenge=true
      - --certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web
      - --certificatesresolvers.letsencrypt.acme.email=your-email@example.com # Set to your email
      - --certificatesresolvers.letsencrypt.acme.storage=/letsencrypt/acme.json # Persist certificates
    ports:
#      - "80:80"    # HTTP traffic
      - "443:443"  # HTTPS traffic
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro # Required for Docker provider
      - ./letsencrypt:/letsencrypt # Persist Let's Encrypt certificates
    networks:
      - dokploy-network # Attach Traefik to the dokploy-network
    labels:
      - traefik.enable=true
      - "traefik.http.routers.dashboard.rule=Host(`dashboard.iotwise.com.au`)" # Dashboard route
      - "traefik.http.routers.dashboard.entrypoints=websecure"
      - "traefik.http.routers.dashboard.service=api@internal"
      - "traefik.http.routers.dashboard.tls.certresolver=letsencrypt"

  telegraf:
    image: 'telegraf:${TELEGRAF_VERSION:-latest}'
    restart: always
    hostname: telegraf
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/config/telegraf.conf:/etc/telegraf/telegraf.conf:ro
      - ./volumes/config/telegraf.d:/etc/telegraf/telegraf.d:ro
    depends_on:
      - influxdb
    networks:
      - dokploy-network
  influxdb:
    image: 'influxdb:1.8'
#    ports:
#      - "8086:8086" # Expose InfluxDB directly
    restart: always
    hostname: influxdb
    environment:
      - 'INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/config/influxdb.conf:/etc/influxdb/influxdb.conf:ro
      - '../files/influxdb:/var/lib/influxdb:rw'
    command: influxd -config /etc/influxdb/influxdb.conf # Referencing custom config
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.influxdb.rule=Host(`${INFLUXDB_HOST:-influxdb.iotwise.com.au}`)
      - traefik.http.routers.influxdb.entrypoints=websecure
      - traefik.http.routers.influxdb.tls.certresolver=letsencrypt
      - traefik.http.services.influxdb.loadbalancer.server.port=8086
  chronograf:
    image: 'chronograf:${CHRONOGRAF_VERSION:-latest}'
#    ports:
#      - "8888:8888" # Expose Chronograf Dashboard directly
    restart: always
    hostname: chronograf
    environment:
      - 'INFLUXDB_URL=http://influxdb:8086'
      - 'INFLUXDB_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'INFLUXDB_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
      - 'KAPACITOR_URL=http://kapacitor:9092'
      - 'KAPACITOR_USERNAME=${INFLUXDB_ADMIN_USER:-admin}'
      - 'KAPACITOR_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-password}'
    volumes:
      - ./volumes/chronograf:/var/lib/chronograf:rw
      - ./scripts/fix_permissions_chronograph.sh:/scripts/entrypoint.sh
    entrypoint: [ "sh", "./scripts/entrypoint.sh" ]
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.chronograf.rule=Host(`${CHRONOGRAF_HOST:-chronograf.iotwise.com.au}`)
      - traefik.http.routers.chronograf.entrypoints=websecure
      - traefik.http.routers.chronograf.tls.certresolver=letsencrypt
      - traefik.http.services.chronograf.loadbalancer.server.port=8888
  kapacitor:
    image: 'kapacitor:${KAPACITOR_VERSION:-latest}'
#    ports:
#      - "9092:9092"  # Expose Kapacitor's default port directly
    restart: always
    hostname: kapacitor
    environment:
      - KAPACITOR_INFLUXDB_0_URLS_0=http://influxdb:8086
      - KAPACITOR_INFLUXDB_0_USERNAME=admin
      - KAPACITOR_INFLUXDB_0_PASSWORD=password
    volumes:
      - ./volumes/config/kapacitor.conf:/etc/kapacitor/kapacitor.conf:ro
      - ./volumes/kapacitor:/var/lib/kapacitor:rw
      - ./scripts/entrypoint.sh:/scripts/entrypoint.sh
    entrypoint: ["sh", "./scripts/entrypoint.sh"]
    depends_on:
      - influxdb
    networks:
      - dokploy-network
    labels:
      - traefik.enable=true
      - >-
        traefik.http.routers.kapacitor.rule=Host(`${KAPACITOR_HOST:-kapacitor.iotwise.com.au}`)
      - traefik.http.routers.kapacitor.entrypoints=websecure
      - traefik.http.routers.kapacitor.tls.certresolver=letsencrypt
      - traefik.http.services.kapacitor.loadbalancer.server.port=9092

networks:
  dokploy-network:
    driver: bridge
